trigger:
  branches:
    include:
      - main  # Cambia esto por el nombre de tu rama principal

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g firebase-tools
    firebase login:ci --no-localhost --token "1//05Zw-1IeSjAbYCgYIARAAGAUSNgF-L9IrXC_PqFA2TAb75pnS8-5wgICBpZGSEAqCVZ1hd7maxEjG0H5J440UVu1d1SwEwEAXHQ"
    firebase deploy --token "1//05Zw-1IeSjAbYCgYIARAAGAUSNgF-L9IrXC_PqFA2TAb75pnS8-5wgICBpZGSEAqCVZ1hd7maxEjG0H5J440UVu1d1SwEwEAXHQ"
  displayName: 'Deploy to Firebase'
